selenium:
  driver:
    type: CHROME
    path: /home/hoangdao/Downloads/chromedriver/chromedriver
  proxy:
    enable: false
    host: localhost
    port: 80
    username: hoangdao
    password: Hoangdao192@
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: crawler
      password: Hoangdao192@
      database: magazine_crawler
